### ISSUE TITLE
dictionary.mat

### ISSUE THREAD

**Issue by ZhengguoTan** [YaminArefeen/latent_signal_models_mrm_2022#1]
Dear Dr. Yamin Arefeen,

Thank you for sharing such an excellent tool! Very impressive work!

I may have a question with regard to the data "dictionary.mat" in the folder "fig07_epti". 

Is dictionary.mat meant for GE-EPTI? 

Thanks,
Zhengguo

**Comment by YaminArefeen** [comment]
Hello Zhengguo,

Thank you for reaching out about this.  "dictionary.mat" in the folder
fig07_epti should be meant for GE-EPTI.

Thanks,
Yamin

**Comment by ZhengguoTan** [comment]
Thank you, Yamin!

**Comment by ZhengguoTan** [comment]
asdf
